name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    # - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
    #   run: |
    #     npm install
    #     npm run build

    - name: '部署到github pages...'
      uses: xRealNeon/VuePagesAction@1.0.0
      with:
        username: 'Jsmond2016'
        reponame: 'github-action-test'
        token: ${{ secrets.ACCESS_TOKEN }} # Leave this line unchanged
    # - name: Build and Deploy
    #   uses: JamesIves/github-pages-deploy-action@4.1.1
    #   with:
    #     token: ${{ secrets.ACCESS_TOKEN }}
    #     branch: gh-pages
    #     folder: dist